# file path to neural network weights and model config
model_name: "GQCNN-4.0-PJ"
model_dir: "/home/michel_ma/Moveit_Deep_Grasp_Demo/models/FC-GQCNN-4.0"
model_params: "/home/michel_ma/Moveit_Deep_Grasp_Demo/dexnet_deps/gqcnn/cfg/examples/replication/dex-net_4.0_pj.yaml"
